# name: hello-world
# on: push
# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: my-step
#         run: echo "Hello Opstree"
#added#
name: CI

'on':
    push:
      branches:
        - main

jobs:
  call-shared-workflow:
    uses: gautam8p/salary-api/.github/workflows/main.yml@main

